### ISSUE TITLE
FreeAgent Authentication

### ISSUE THREAD

**Issue by russellseymour** [6by6/freeagent-php#3]
I am trying to use this library to access FA and create custom reports, however I am failing at the first hurdle.

Does the library handle the authentication requests with the necessary redirects?  I see from the README that the `clientId`, `clientSecret` and `refreshToken` are required when setting up the API.  Does this mean that the initial OAuth has to be done before calling the library?

When I try to use it without the refreshToken I get an `invalid_grant` error which is probably to be expected.

Thanks.

**Comment by daniel-ness** [comment]
Hi @russellseymour 

Yes, that's correct. We're primarily using this library for backend tasks so it has been developed assuming that the `refreshToken` has already been obtained. You can follow the guide at https://dev.freeagent.com/docs/quick_start to find out how to do so through OAuth Playground. Give me a shout if you have any further problems though.
